import os
from dotenv import load_dotenv
load_dotenv()

CYCLE_SECONDS = 60
NB_AGENTS_OPERATIONNELS = 1000
NB_HUB_BROKERS = 250
NB_DIRECTION = 100
NB_FINANCE = 150
NB_API_CONVERT = 50
NB_AGENTS_TOTAL = NB_AGENTS_OPERATIONNELS + NB_HUB_BROKERS + NB_DIRECTION + NB_FINANCE + NB_API_CONVERT
NB_BOOSTERS_TOTAL = 500

NB_AFFILIATION = 300
NB_MICROTASK = 200
NB_CONTENU = 200
NB_ARBITRAGE = 150
NB_STAKING = 100
NB_API_CREATOR = 50

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
INFURA_PROJECT_ID = os.getenv("INFURA_PROJECT_ID", "")
INFURA_SECRET = os.getenv("INFURA_SECRET", "")
WALLET_PRIVATE_KEY = os.getenv("WALLET_PRIVATE_KEY", "")
WALLET_ADDRESS = os.getenv("WALLET_ADDRESS", "")
BSC_RPC = "https://bsc-dataseed.binance.org"

WALLET_FILE = "wallet.json"
STATE_FILE = "state.json"
LOG_FILE = "business.log"
