github.com:
    users:
        francky07:
            oauth_token: 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
    git_protocol: ssh
    user: francky07
    oauth_token: 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
